# Default values for python-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: rizatdinov/python_app
  pullPolicy: IfNotPresent
  tag: "gh-actions-1fb1c0e0bab31de41e9efad049d60bffc93813a8"

configmap:
  config:
    name: my-configmap

secrets:
  config:
    name: test-secret
  lab: eleven

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: python-app-service
  type: LoadBalancer
  port: 8000

statefulSet:
  podManagementPolicy: "Parallel"
  volumeClaimTemplates:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128M

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100

nodeSelector: {}

tolerations: []

affinity: {}
