
# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# In order to use vagrant-ansible for fast debugging
# References:
# * https://docs.ansible.com/ansible/latest/scenario_guides/guide_vagrant.html

# Box / OS
VAGRANT_BOX = 'bento/ubuntu-20.04'

# VM configuration parameteres
VM_NAME = 'test-machine'
VM_MEMORY = 2048
VM_GUI = true
VM_CPUS = 2

HOST_PORT_APP = 8001
HOST_PORT_GRAPHANA = 3001
HOST_PORT_PROMTAIL = 9081

GUEST_PORT_APP = 8000
GUEST_PORT_GRAPHANA = 3000
GUEST_PORT_PROMTAIL = 9080

Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "forwarded_port", guest: GUEST_PORT_APP, host: HOST_PORT_APP
  config.vm.network "forwarded_port", guest: GUEST_PORT_GRAPHANA, host: HOST_PORT_GRAPHANA
  config.vm.network "forwarded_port", guest: GUEST_PORT_PROMTAIL, host: HOST_PORT_PROMTAIL

  config.vm.provider "virtualbox" do |v|
          v.memory = VM_MEMORY
          v.cpus = VM_CPUS
          v.gui = VM_GUI
  end

  config.vm.provision "ansible" do |ansible|
          ansible.playbook = "./playbooks/main.yml"
          ansible.config_file = "./ansible.cfg"
  end
end
