---
# References: https://docs.ansible.com/ansible/2.9/modules/docker_compose_module.html
- name: Create application folder
  file:
    path: "{{ python_app_workdir }}"
    state: directory
    mode: '0755'

- name: Create promtail configuration folder
  file:
    path: "{{ promtail_configdir }}"
    state: directory
    mode: '0755'

- name: Create prometheus configuration folder
  file:
    path: "{{ prometheus_configdir }}"
    state: directory
    mode: '0755'

- name: Copy promtail config file to virtual machine
  template:
    src: promtail.yaml.j2
    dest: "{{ promtail_configdir }}/promtail.yaml"
    mode: '0755'

- name: Copy prometheus config file to virtual machine
  template:
    src: prometheus.yaml.j2
    dest: "{{ prometheus_configdir }}/prometheus.yml"
    mode: '0755'

- name: Copy docker-compose file to virtual machine
  template:
    src: docker-compose.yaml.j2
    dest: "{{ python_app_workdir }}/docker-compose.yaml"
    mode: '0700'

- name: Deploy application with docker-compose
  community.docker.docker_compose:
    build: no
    pull: yes
    state: present
    project_src: "{{ python_app_workdir }}"
