---
- name: Ensure pip3 is installed
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Ensure python docker dependencies are installed
  pip:
    name:
      - docker
      - docker-compose
    state: present
